### ISSUE TITLE
MapsCamp 2016 Post Mortem

### ISSUE THREAD

**Issue by jgravois** [MapsCamp/MapsCamp#25]
Overall, i'd label MapsCamp a **big** success, thanks to the speakers, organizing crew and the support of OpenCamps czars.  speaking on behalf of Esri, we were absolutely pleased to participate and look forward to seeing what shakes out next year.

now that the dust has settled down, i thought it would be helpful to jot down notes with regard to the day.
### what worked:
1. the room - we were **almost** beyond the capacity of our assigned room, but i liked the coziness and fullness.
2. the content - the speakers were exceptional and the content was engaging.  my impression was that folks really enjoyed the panels too.
3. by mid-morning break there were enough OpenCamps staff present to deliver snacks, answer questions and assist with facilities related questions.
#### check in
1. the visitor center across the street wasn't open until 10am.
2. there was no signage/staff outside the UN gates to corral individual camps
3. UN security did not have a list of the folks that RSVPed
4. the OpenCamps contracted staff that finally arrived outside the gates at 8:30 did not have a list of RSVPs, signage, or a clue as to how to proceed.
5. Forest arrived at about 8:45, also without a list of attendees, and just passed out tickets freely.
6. there wasn't any OpenCamps signage or staff _inside_ the UN facility upstairs to lead folks down to their respective camps
#### lunch
1. a single line to get food - breaking out the sandwich tables into multiple lines would have helped considerably.
2.   there weren't sufficient tables and chairs for all attendees to sit down and eat.
#### general
1. tickets - was it intentional that initially only $20 tickets were available on eventbrite?  it seemed strange to me that it only became possible to RSVP _gratis_ a few days prior to the actual event.
2. a second projector - [Stanley](https://twitter.com/stanographer) who transcribed all the talks was expecting his work to be projected for the hearing impaired, but we only had one projector.

if i've missed anything, or if any of my comments are off base, _please_ chime in.

**Comment by namessanti** [comment]
Looks like you got everything to me @jgravois

**Comment by courtneycl** [comment]
I left without a good sense of who was there. The breaks and lunchtime were good opportunities to meet new people, but I couldn't tell who was in mapscamp and who was in another camp. Separate name tags for each camp might be useful. 

Panels could have been longer. 

+1 for the great presentations - there was a good mix of content.
